/**
 * Freebuff — Electron main process (the shell side of the
 * Electron-shell + Bun-orchestrator split described in the PRD §6 and README).
 *
 * Electron's main process runs Node, not Bun. To honor "Bun main process"
 * (reuse sdk/ + agent-runtime, which export Bun-targeted TS) the shell spawns
 * the Bun orchestrator as a child process and talks to it over local HTTP/SSE
 * on 127.0.0.1. The renderer is the existing self-contained UI the Bun server
 * serves, so there is no separate renderer build step.
 *
 * Two run modes, see resolveOrchestrator():
 *   - dev: spawn a system `bun` on the TS source (src/server/main.ts).
 *   - packaged: spawn the Bun binary shipped in app resources on the pre-bundled
 *     orchestrator.js (scripts/fetch-bun.ts + scripts/build-orchestrator.ts,
 *     wired into the app via the electron-builder extraResources config). The
 *     user needs no system Bun.
 *
 *   bun --cwd freebuff-desktop run app        # launch from source (dev)
 */

const { app, BrowserWindow, Menu, shell, dialog, ipcMain, webContents } = require('electron')
const { spawn } = require('node:child_process')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const net = require('node:net')
const http = require('node:http')
const updater = require('./updater.cjs')
const { packagedBunPath } = require('./packaged-bun-path.cjs')
const { createCdpBridge } = require('./cdp-bridge.cjs')
const { resolveRevealTarget } = require('./reveal-path.cjs')
const { fixPath } = require('./shell-path.cjs')
const { detectSigning } = require('./signing.cjs')

// Keep the last ~3000 chars of orchestrator stderr for the failure dialog.
const STDERR_TAIL_CHARS = 3000
function appendTail(tail, text) {
  return (tail + text).slice(-STDERR_TAIL_CHARS)
}

function describeFailure(failure) {
  const detailParts = []
  if (failure.errorMessage) detailParts.push(failure.errorMessage)
  if (failure.kind === 'timeout') detailParts.push('The orchestrator did not become ready in time.')
  if (failure.code !== undefined || failure.signal) {
    detailParts.push(`Process ended (code ${failure.code ?? 'none'}, signal ${failure.signal ?? 'none'}).`)
  }
  if (failure.stderrTail) detailParts.push(`\nRecent log output:\n${failure.stderrTail.trim()}`)
  return {
    message: 'The Freebuff orchestrator failed to start or stopped unexpectedly.',
    detail: detailParts.join('\n'),
  }
}

// Launched from Finder/Dock, launchd gives us a minimal PATH with no Homebrew and
// no ~/.bun/bin, and every child inherits it — so the orchestrator and its agent
// harnesses can't find `bun`, `codex`, or anything else the user installed. Repair
// PATH from the login shell HERE, at module load, before a single child is spawned.
//
// Runs before `app` is ready (so no log dir yet): buffer the one-line diagnostic
// and flush it into the orchestrator log once createStderrCapture establishes the
// dir. This is the SECOND silent "Codex not found only in the packaged build" PATH
// bug — the breadcrumb makes any third one a log read, not a repro hunt.
let pathRepairDiag = ''
fixPath({
  log: (line) => {
    pathRepairDiag = line
    console.error(line)
  },
})

// In-app update checker (see updater.cjs). Wired up once boot succeeds; the
// "Check for Updates…" menu item calls through this handle. Null until boot.
/** @type {{ checkNow: (opts?: {interactive?: boolean}) => Promise<void> } | null} */
let updateChecker = null

function checkForUpdatesInteractive() {
  void updateChecker?.checkNow({ interactive: true })
}

const PKG_DIR = path.join(__dirname, '..')
// The packaged app's Info.plist / .ico / .png bundle the right icon, but in dev
// the OS would otherwise show Electron's default icon. Point at our PNG so dev
// looks the same as packaged. The file is generated by scripts/build-icon.ts.
const APP_ICON_PATH = path.join(PKG_DIR, 'build', 'icon.png')

/** @type {import('node:child_process').ChildProcess | null} */
let serverProc = null
// Port the orchestrator listens on (set in boot); crash restarts reuse it so
// appUrl/appOrigin stay valid and the renderer just reconnects.
/** @type {number | null} */
let serverPort = null
// Crash-restart budget: up to 3 respawns; refreshed after 60s of uptime.
let restartAttempts = 0
let lastSpawnAt = 0
// loopback cdp bridge (cdp-bridge.cjs): the only channel through which the orchestrator can
// drive a preview <webview>, since webContents.debugger is a main-process api
let cdpBridge = null
/** @type {BrowserWindow | null} */
let mainWindow = null
// How this copy is signed (signing.cjs) — probed once in boot(), ships to the
// orchestrator via env so it rides the launch analytics event.
/** @type {{ state: string, team?: string } | null} */
let signing = null
let shuttingDown = false
// The single trusted origin the renderer is allowed to live at (set in boot()
// once the orchestrator port is known). Navigation / new-window requests to any
// other origin are denied and handed to the system browser, so the preload
// bridge never rides along to an untrusted document.
/** @type {string | null} */
let appOrigin = null
// The URL the renderer loads (orchestrator origin, or the Vite dev server). Held
// at module scope so a macOS dock re-activate can reattach to the live
// orchestrator instead of spawning a second one.
/** @type {string | null} */
let appUrl = null

// Override package.json's "@codebuff/freebuff-desktop" name — that string leaks
// into the macOS app menu, About panel, and Windows taskbar/AppUserModelId.
app.setName('Freebuff')
app.setAppUserModelId('com.freebuff.desktop')
if (process.platform === 'darwin' && app.setAboutPanelOptions) {
  app.setAboutPanelOptions({ name: 'Freebuff' })
}

function resolveOrchestrator() {
  if (app.isPackaged) {
    const res = process.resourcesPath
    const orchDir = path.join(res, 'orchestrator')
    return {
      // FREEBUFF_BUN_PATH overrides the bundled binary in tests and diagnostics.
      bun:
        process.env.FREEBUFF_BUN_PATH ||
        packagedBunPath(process.resourcesPath, process.platform),
      args: [path.join(orchDir, 'orchestrator.js')],
      cwd: orchDir,
      uiDir: path.join(orchDir, 'ui'),
      packaged: true,
    }
  }
  // No --watch by default. Bun's watch mode re-executes the entry IN THE SAME PROCESS and
  // delivers no signal on the way, which defeats three things at once: the SIGTERM handler in
  // main.ts never runs, so beginShutdown() never settles live turns (they stay `running` in the
  // db with nothing behind them, which is what a "frozen" tab actually is); the orphan reaper
  // skips every harness CLI the previous incarnation spawned, because they carry
  // FREEBUFF_ORCHESTRATOR_PID equal to the pid still running (orphan-reaper.ts reads them as our
  // own live children), so each reload leaks a claude/codex process; and the close handler below
  // never fires, so Electron's crash-restart budget cannot see any of it. boot() then auto-resumes
  // the interrupted turn while the leaked CLI is still editing the same files.
  // Restarting the app is the recovery precisely because a new pid makes the orphans visible again.
  // FREEBUFF_DEV_WATCH=1 opts back in for sessions that only touch pure modules with no turn running.
  const watch = process.env.FREEBUFF_DEV_WATCH === '1' ? ['--watch', '--no-clear-screen'] : []
  return {
    bun: process.env.FREEBUFF_BUN_PATH || 'bun',
    args: [...watch, path.join(PKG_DIR, 'src', 'server', 'main.ts')],
    cwd: PKG_DIR,
    // In dev the built dist-ui/ may exist (after `ui:build`); the server falls
    // back to it. When FREEBUFF_DEV_UI is set, the Vite dev server serves the UI.
    uiDir: undefined,
    packaged: false,
  }
}

// Ask the OS for an unused loopback port so two instances never collide.
function findFreePort() {
  return new Promise((resolve, reject) => {
    const srv = net.createServer()
    srv.unref()
    srv.on('error', reject)
    srv.listen(0, '127.0.0.1', () => {
      const { port } = srv.address()
      srv.close(() => resolve(port))
    })
  })
}

// Poll the orchestrator's /healthz until it answers (or we give up). Using the
// trivial liveness probe instead of /api/state keeps readiness from depending on
// the full engine snapshot serializing.
function waitForServer(port, timeoutMs = 30000, shouldStop = () => false) {
  const start = Date.now()
  return new Promise((resolve, reject) => {
    const retry = () => {
      if (shouldStop()) {
        reject(new Error('orchestrator stopped before becoming ready'))
      } else if (Date.now() - start >= timeoutMs) {
        reject(new Error(`orchestrator did not come up within ${timeoutMs}ms`))
      } else {
        setTimeout(attempt, 300)
      }
    }
    const attempt = () => {
      if (shouldStop() || Date.now() - start >= timeoutMs) {
        retry()
        return
      }
      let attemptSettled = false
      const retryAttempt = () => {
        if (attemptSettled) return
        attemptSettled = true
        retry()
      }
      const req = http.get(
        { host: '127.0.0.1', port, path: '/healthz', timeout: 1500 },
        (res) => {
          res.resume()
          if (res.statusCode === 200) {
            attemptSettled = true
            resolve()
          } else {
            retryAttempt()
          }
        },
      )
      req.on('error', retryAttempt)
      req.on('timeout', () => req.destroy())
    }
    attempt()
  })
}

function createStderrCapture(bun, args) {
  let logPath = null
  let stderrTail = ''
  let writable = true
  try {
    const logDir = app.getPath('logs')
    fs.mkdirSync(logDir, { recursive: true })
    logPath = path.join(logDir, 'orchestrator-stderr.log')
    const header =
      `[${new Date().toISOString()}] Starting Freebuff orchestrator\n` +
      `Runtime: ${bun}\nArguments: ${args.join(' ')}\n` +
      (pathRepairDiag ? `${pathRepairDiag}\n` : '') +
      `\n`
    if (restartAttempts > 0) {
      // Crash restart: append with a marker so the crashed instance's log survives.
      fs.appendFileSync(logPath, `\n[restart ${restartAttempts}] ${header}`)
    } else {
      // Recreate the file so a permissive mode from an older app version cannot
      // survive the mode passed to writeFileSync (which only applies on create).
      fs.rmSync(logPath, { force: true })
      fs.writeFileSync(logPath, header, { mode: 0o600 })
    }
  } catch (err) {
    writable = false
    logPath = null
    console.error('[orchestrator] could not create stderr log:', err?.message ?? err)
  }

  return {
    get logPath() {
      return logPath
    },
    get stderrTail() {
      return stderrTail
    },
    write(chunk) {
      const text = Buffer.isBuffer(chunk) ? chunk.toString('utf8') : String(chunk)
      stderrTail = appendTail(stderrTail, text)
      if (!writable || !logPath) return
      try {
        fs.appendFileSync(logPath, text)
      } catch (err) {
        writable = false
        console.error('[orchestrator] could not append to stderr log:', err?.message ?? err)
      }
    },
  }
}

async function showOrchestratorFailure(failure, parent = mainWindow) {
  const { message, detail } = describeFailure(failure)
  const buttons = []
  const actions = []
  if (failure.logPath) {
    buttons.push('Show Log')
    actions.push(() => shell.showItemInFolder(failure.logPath))
  }
  buttons.push('Quit')
  actions.push(() => {})

  const options = {
    type: 'error',
    title: 'Freebuff failed to start',
    message,
    detail,
    buttons,
    defaultId: 0,
    cancelId: buttons.length - 1,
    noLink: true,
  }
  const usableParent = parent && !parent.isDestroyed() ? parent : null
  const response = usableParent
    ? dialog.showMessageBoxSync(usableParent, options)
    : dialog.showMessageBoxSync(options)
  try {
    await actions[response]?.()
  } catch (err) {
    console.error('[orchestrator] diagnostic action failed:', err?.message ?? err)
  }
}

function startOrchestrator(port) {
  return new Promise((resolve, reject) => {
    const { bun, args, cwd, uiDir, packaged } = resolveOrchestrator()
    const capture = createStderrCapture(bun, args)
    let exited = false
    let ready = false
    let startupSettled = false

    const failure = (kind, fields = {}) => ({
      kind,
      bunPath: bun,
      platform: process.platform,
      logPath: capture.logPath,
      stderrTail: capture.stderrTail,
      ...fields,
    })
    const rejectStartup = (diagnostic) => {
      if (startupSettled) return
      startupSettled = true
      const err = new Error(describeFailure(diagnostic).message)
      err.orchestratorFailure = diagnostic
      reject(err)
    }

    // extraResources can lose the executable bit when unpacked; restore it.
    if (packaged && process.platform !== 'win32') {
      try {
        fs.chmodSync(bun, 0o755)
      } catch {
        /* best-effort */
      }
    }

    const env = {
      ...process.env,
      PORT: String(port),
      // The Bun process owns telemetry, but only Electron knows the installed
      // package version. Pass it across so renderer crashes group by release.
      FREEBUFF_APP_VERSION: app.getVersion(),
    }
    if (uiDir) env.FREEBUFF_UI_DIR = uiDir
    if (signing) {
      env.FREEBUFF_SIGNING_STATE = signing.state
      if (signing.team) env.FREEBUFF_SIGNING_TEAM = signing.team
    }
    // only this child ever learns the bridge's port and bearer token
    if (cdpBridge) {
      env.FREEBUFF_CDP_BRIDGE_PORT = String(cdpBridge.port)
      env.FREEBUFF_CDP_BRIDGE_TOKEN = cdpBridge.token
    }

    lastSpawnAt = Date.now()
    const proc = spawn(bun, args, {
      cwd,
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    serverProc = proc

    proc.on('error', (err) => {
      exited = true
      capture.write(`[launcher] ${err.message}\n`)
      if (serverProc === proc) serverProc = null
      rejectStartup(
        failure('spawn', {
          errorMessage:
            `Failed to start the orchestrator with "${bun}": ${err.message}. ` +
            (packaged
              ? 'The bundled Bun runtime could not be launched.'
              : 'Make sure Bun is installed or set FREEBUFF_BUN_PATH.'),
        }),
      )
    })

    proc.stdout.on('data', (d) => process.stdout.write(`[orchestrator] ${d}`))
    proc.stderr.on('data', (d) => {
      capture.write(d)
      process.stderr.write(`[orchestrator] ${d}`)
    })

    // `exit` can precede the final stderr chunks. Mark the process dead here so
    // readiness polling stops, but build diagnostics on `close`, after stdio is
    // fully drained into the excerpt and log file.
    proc.once('exit', () => {
      exited = true
    })

    proc.once('close', (code, signal) => {
      exited = true
      const pid = proc.pid
      if (serverProc === proc) serverProc = null
      if (shuttingDown) return
      console.error(`[orchestrator] process ${pid} ended (code ${code ?? 'none'}, signal ${signal ?? 'none'})`)
      const diagnostic = failure(ready ? 'runtime' : 'exit', { code, signal })
      if (!ready) {
        rejectStartup(diagnostic)
      } else {
        void restartOrchestrator(diagnostic)
      }
    })

    waitForServer(port, 30000, () => exited).then(
      () => {
        if (exited || startupSettled) return
        ready = true
        startupSettled = true
        resolve()
      },
      () => {
        if (exited) return
        // Still alive but never became ready: kill it, or the orphan keeps the
        // port and every respawn on the same port EADDRINUSEs.
        proc.kill('SIGKILL')
        rejectStartup(failure('timeout'))
      },
    )
  })
}

// A post-ready orchestrator exit gets a respawn on the same port (appUrl/appOrigin
// stay valid, so the renderer's SSE client reconnects and resyncs on its own — no
// window reload). The fatal dialog is reserved for a genuine crash loop: 3 failed
// restarts without 60s of uptime in between.
async function restartOrchestrator(diagnostic) {
  while (!shuttingDown) {
    if (Date.now() - lastSpawnAt > 60_000) restartAttempts = 0 // stayed up → fresh budget
    if (restartAttempts >= 3) break
    restartAttempts++
    try {
      await startOrchestrator(serverPort)
      return
    } catch (err) {
      diagnostic = err?.orchestratorFailure ?? diagnostic
    }
  }
  if (shuttingDown) return
  await showOrchestratorFailure(diagnostic)
  app.quit()
}

function stopOrchestrator() {
  shuttingDown = true
  if (cdpBridge) {
    void cdpBridge.close()
    cdpBridge = null
  }
  if (serverProc && !serverProc.killed) {
    serverProc.kill('SIGTERM')
    // Hard-stop if it ignores the polite request.
    const proc = serverProc
    setTimeout(() => {
      // ChildProcess.killed only means kill() was called; it becomes true before
      // the child actually exits, so it cannot tell us whether SIGTERM worked.
      if (proc.exitCode === null && proc.signalCode === null) proc.kill('SIGKILL')
    }, 3000)
  }
}

function loadingPage() {
  // Inline splash shown while the orchestrator boots. Matches the UI's dark +
  // freebuff-lime palette so the transition isn't jarring.
  const html = `<!doctype html><html><head><meta charset="utf-8">
<style>
  html,body{height:100%;margin:0}
  /* frameless (linux) has no native frame while booting, so the splash itself must be draggable */
  body{-webkit-app-region:drag;display:flex;align-items:center;justify-content:center;flex-direction:column;
    gap:18px;background:#0c0d0f;color:#e6e6e6;
    font:14px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
  .dot{width:42px;height:42px;border-radius:50%;
    border:3px solid #1f2937;border-top-color:#7cff3f;animation:spin 0.9s linear infinite}
  .msg{color:#9ca3af}
  @keyframes spin{to{transform:rotate(360deg)}}
</style></head><body>
  <div class="dot"></div>
  <div class="msg">Starting Freebuff orchestrator…</div>
</body></html>`
  return `data:text/html;charset=utf-8,${encodeURIComponent(html)}`
}

/** Whether `url` is same-origin with the trusted app origin (set in boot()).
 *  False before boot resolves the origin, or for an unparseable URL. */
function isAppUrl(url) {
  if (!appOrigin) return false
  try {
    return new URL(url).origin === appOrigin
  } catch {
    return false
  }
}

/** Hand an off-origin link to the system browser — but only http(s), so a
 *  malicious document can't get the OS to launch a file:/custom-scheme URL.
 *  Resolves false when the URL is unsafe or the OS rejects the open request. */
async function openExternal(url) {
  try {
    const parsed = new URL(url)
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return false
    await shell.openExternal(parsed.toString())
    return true
  } catch {
    return false
  }
}


/** Whether `url` is a loopback http(s) URL — the only thing the Preview tab's
 *  <webview> may load (a dev server is by definition local). */
function isLoopbackHttpUrl(url) {
  try {
    const parsed = new URL(url)
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return false
    const host = parsed.hostname.toLowerCase()
    return host === 'localhost' || host === '127.0.0.1' || host === '::1' || host === '[::1]'
  } catch {
    return false
  }
}

// Constrain every <webview> the renderer attaches (the Preview tab is the only
// creator, but the guard holds regardless): no preload / node, loopback-only
// content, and window.open/off-loopback navigation diverted to the system
// browser so the preview can never wander into a privileged or remote page.
app.on('web-contents-created', (_event, contents) => {
  contents.on('will-attach-webview', (event, webPreferences, params) => {
    delete webPreferences.preload
    webPreferences.nodeIntegration = false
    webPreferences.contextIsolation = true
    if (!isLoopbackHttpUrl(params.src)) event.preventDefault()
  })
  if (contents.getType() === 'webview') {
    contents.setWindowOpenHandler(({ url }) => {
      void openExternal(url)
      return { action: 'deny' }
    })
    contents.on('will-navigate', (event, url) => {
      if (isLoopbackHttpUrl(url)) return
      event.preventDefault()
      void openExternal(url)
    })
  }
})

// One shape for push ('window-state') and pull ('window:state'): mac's
// fullscreen traffic-light inset and the frameless maximize/restore glyph both
// render from it.
function windowState(win) {
  return { fullScreen: win.isFullScreen(), maximized: win.isMaximized() }
}

function createWindow() {
  // Linux otherwise stacks three rows of chrome (WM title bar, Electron menu
  // bar, our tab bar): go frameless there with the menu auto-hidden (Alt
  // reveals it; accelerators still fire) and let the renderer draw the window
  // buttons. macOS keeps hiddenInset; Windows keeps its frame for Snap Layouts.
  const frameless = process.platform === 'linux'
  const winOpts = {
    width: 1440,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    backgroundColor: '#0c0d0f',
    title: 'Freebuff',
    frame: !frameless,
    autoHideMenuBar: frameless,
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      // The sandboxed preload can only require built-ins, so it learns whether
      // to draw a title bar from an argv flag derived from THIS window's frame
      // option — the two can't disagree.
      additionalArguments: [`--custom-title-bar=${frameless ? '1' : '0'}`],
      // The explorer panel's Preview tab embeds the thread's dev server in a
      // <webview> — its own webContents per preview (unprivileged; see the
      // will-attach-webview guard). Loading is confined to loopback servers.
      webviewTag: true,
    },
  }
  if (fs.existsSync(APP_ICON_PATH)) winOpts.icon = APP_ICON_PATH

  mainWindow = new BrowserWindow(winOpts)

  const sendWindowState = () => {
    if (!mainWindow || mainWindow.webContents.isDestroyed()) return
    mainWindow.webContents.send('window-state', windowState(mainWindow))
  }
  mainWindow.on('enter-full-screen', sendWindowState)
  mainWindow.on('leave-full-screen', sendWindowState)
  // The maximize/restore glyph follows the WINDOW, not the click — WM-side
  // tiles, snaps, and drag-region double-clicks must update it too.
  mainWindow.on('maximize', sendWindowState)
  mainWindow.on('unmaximize', sendWindowState)
  mainWindow.webContents.on('did-finish-load', sendWindowState)

  mainWindow.loadURL(loadingPage())

  // New windows: only the trusted app origin may open in-app (with the preload
  // bridge attached); every other URL is denied and opened in the system browser.
  // A broad "any localhost" allow would let a malicious preview link load another
  // local service in a privileged window. http(s) only — never hand the OS a
  // file:/custom-scheme URL.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (isAppUrl(url)) return { action: 'allow' }
    void openExternal(url)
    return { action: 'deny' }
  })

  // Top-level navigation: keep the renderer pinned to the app origin so the
  // preload surface can't travel to an untrusted document. Off-origin link
  // clicks are cancelled and sent to the system browser instead.
  mainWindow.webContents.on('will-navigate', (event, url) => {
    if (isAppUrl(url)) return
    event.preventDefault()
    void openExternal(url)
  })

  mainWindow.on('closed', () => {
    mainWindow = null
  })

  return mainWindow
}

// Forward a tab command to the renderer, which owns tab state. The renderer also
// handles these via keydown; in Electron the menu accelerator consumes the keys so
// only this IPC path fires (no double-action).
function sendMenuCommand(name) {
  mainWindow?.webContents.send('menu-cmd', name)
}

// Paperclip → native open dialog. Allows files AND folders (multi-select), and
// stats each pick so the renderer can label folders vs. files. Returns [] when the
// user cancels.
ipcMain.handle('dialog:pickAttachments', async () => {
  if (!mainWindow) return []
  const res = await dialog.showOpenDialog(mainWindow, {
    title: 'Attach files or folders',
    buttonLabel: 'Attach',
    properties: ['openFile', 'openDirectory', 'multiSelections', 'treatPackageAsDirectory'],
  })
  if (res.canceled) return []
  return res.filePaths.map((p) => {
    let isDirectory = false
    try {
      isDirectory = fs.statSync(p).isDirectory()
    } catch {
      /* unreadable — treat as a file */
    }
    return { path: p, name: path.basename(p), isDirectory }
  })
})

// Project picker → native folder chooser. Lets the user jump anywhere (home,
// favorites, type a path) instead of drilling the in-app browser from wherever
// it happens to start. Returns the chosen absolute path, or null on cancel.
ipcMain.handle('dialog:pickDirectory', async () => {
  if (!mainWindow) return null
  const res = await dialog.showOpenDialog(mainWindow, {
    title: 'Open a project folder',
    buttonLabel: 'Open',
    properties: ['openDirectory', 'createDirectory'],
  })
  return res.canceled || res.filePaths.length === 0 ? null : res.filePaths[0]
})

// Paste-to-attach: a pasted screenshot has no file path, so the renderer hands us
// the raw bytes and we write them to a temp file the attachment pipeline can read.
// `ext` is sanitized to a short alnum token. Returns { path, name } or null.
ipcMain.handle('clipboard:saveImage', async (_e, { bytes, ext }) => {
  try {
    const safeExt = String(ext || 'png').toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 8) || 'png'
    const dir = path.join(os.tmpdir(), 'freebuff-desktop-pastes')
    fs.mkdirSync(dir, { recursive: true })
    const file = path.join(dir, `paste-${Date.now()}-${process.pid}.${safeExt}`)
    fs.writeFileSync(file, Buffer.from(bytes))
    return { path: file, name: path.basename(file) }
  } catch {
    return null
  }
})

// Pre-send image previews use the same local path the agent receives, but the
// renderer cannot safely load arbitrary file:// URLs under context isolation.
// Keep this deliberately narrow: known image extensions, regular files, and a
// bounded payload returned as a data URL.
ipcMain.handle('attachment:readImage', async (_event, filePath) => {
  const mediaTypes = {
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.bmp': 'image/bmp',
    '.svg': 'image/svg+xml',
    '.avif': 'image/avif',
  }
  try {
    const target = String(filePath || '')
    const mediaType = mediaTypes[path.extname(target).toLowerCase()]
    if (!path.isAbsolute(target) || !mediaType) return null
    const stat = fs.statSync(target)
    if (!stat.isFile() || stat.size > 10 * 1024 * 1024) return null
    return `data:${mediaType};base64,${fs.readFileSync(target).toString('base64')}`
  } catch {
    return null
  }
})

// Recovery flows (e.g. the "Claude Code is signed out" card) hand the user off
// to a real terminal they can type `claude /login` into. mac-only (stock
// Terminal.app, at its modern path with the pre-Catalina one as fallback);
// other platforms resolve false and the renderer hides the button — the
// copyable command is the whole flow there. shell.openPath resolves '' on
// success and an error string on failure, so the renderer can show feedback.
ipcMain.handle('shell:openTerminal', async () => {
  if (process.platform !== 'darwin') return false
  for (const terminalApp of [
    '/System/Applications/Utilities/Terminal.app',
    '/Applications/Utilities/Terminal.app',
  ]) {
    if ((await shell.openPath(terminalApp)) === '') return true
  }
  return false
})

// Open a web URL directly through Electron instead of renderer `window.open`.
// Sign-in obtains its URL asynchronously, after Chromium's popup activation
// window may have elapsed; this IPC path remains reliable and keeps the same
// http(s)-only boundary as link navigation above.
ipcMain.handle('shell:openExternal', (_event, url) => openExternal(url))

ipcMain.handle('shell:revealChange', async (_event, { root, relativePath }) => {
  try {
    const target = resolveRevealTarget(root, relativePath)
    if (!target) return false
    if (target.directoryOnly) return (await shell.openPath(target.path)) === ''
    shell.showItemInFolder(target.path)
    return true
  } catch {
    return false
  }
})

ipcMain.handle('window:state', (event) => {
  const win = BrowserWindow.fromWebContents(event.sender)
  return win ? windowState(win) : { fullScreen: false, maximized: false }
})

// Frameless (Linux) title-bar buttons. Preview content can't reach these — a
// <webview> gets no preload at all (see will-attach-webview), so it has no
// ipcRenderer; acting on the sender's window is just belt-and-braces. Results
// come back on 'window-state' like any WM-driven change.
ipcMain.handle('window:minimize', (event) => {
  BrowserWindow.fromWebContents(event.sender)?.minimize()
})

ipcMain.handle('window:toggleMaximize', (event) => {
  const win = BrowserWindow.fromWebContents(event.sender)
  if (win?.isMaximized()) win.unmaximize()
  else win?.maximize()
})

// close(), not destroy(), so shutdown runs the same as a native close.
ipcMain.handle('window:close', (event) => {
  BrowserWindow.fromWebContents(event.sender)?.close()
})

function buildMenu(reloadApp) {
  const isMac = process.platform === 'darwin'
  // Custom File/Window menus (no default Cmd+W "Close Window" binding) so Cmd+W
  // closes the active TAB, not the window.
  const template = [
    // On mac, build the app menu by hand (instead of `role: 'appMenu'`) so we can
    // slot a native-feeling "Check for Updates…" item right under About.
    ...(isMac
      ? [
          {
            label: app.name,
            submenu: [
              { role: 'about' },
              { label: 'Check for Updates…', click: () => checkForUpdatesInteractive() },
              { type: 'separator' },
              { role: 'services' },
              { type: 'separator' },
              { role: 'hide' },
              { role: 'hideOthers' },
              { role: 'unhide' },
              { type: 'separator' },
              { role: 'quit' },
            ],
          },
        ]
      : []),
    {
      label: 'File',
      submenu: [
        {
          label: 'New Tab',
          accelerator: 'CmdOrCtrl+T',
          click: () => sendMenuCommand('new-tab'),
        },
        {
          label: 'Reopen Closed Tab',
          accelerator: 'CmdOrCtrl+Shift+T',
          click: () => sendMenuCommand('reopen-tab'),
        },
        { label: 'Close Tab', accelerator: 'CmdOrCtrl+W', click: () => sendMenuCommand('close-tab') },
        { type: 'separator' },
        isMac ? { role: 'close', label: 'Close Window', accelerator: 'CmdOrCtrl+Shift+W' } : { role: 'quit' },
      ],
    },
    { role: 'editMenu' },
    {
      label: 'View',
      submenu: [
        { label: 'Reload App', accelerator: 'CmdOrCtrl+R', click: () => reloadApp() },
        { role: 'toggleDevTools' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
    { label: 'Window', submenu: [{ role: 'minimize' }, { role: 'zoom' }] },
    // Non-mac has no app menu, so "Check for Updates…" lives under Help.
    ...(isMac
      ? []
      : [
          {
            label: 'Help',
            submenu: [
              { label: 'Check for Updates…', click: () => checkForUpdatesInteractive() },
            ],
          },
        ]),
  ]
  Menu.setApplicationMenu(Menu.buildFromTemplate(template))
}

// macOS shows the Dock / Cmd+Tab icon from the running .app bundle, NOT from a
// BrowserWindow's `icon` option (that one is ignored on macOS). In the packaged
// app the bundled icon.icns covers this, but in dev the running bundle is
// Electron's own, so without this the switcher shows the Electron logo. Setting
// the dock icon at runtime fixes both Dock and Cmd+Tab in dev. (The Cmd+Tab
// *name* comes from the bundle's CFBundleName, which has no runtime API — see
// scripts/brand-dev-electron.ts for the dev-only fix.)
function applyDockIcon() {
  if (process.platform !== 'darwin' || !app.dock) return
  try {
    if (fs.existsSync(APP_ICON_PATH)) app.dock.setIcon(APP_ICON_PATH)
  } catch {
    /* best-effort — a bad icon shouldn't stop the app booting */
  }
}

async function boot() {
  applyDockIcon()
  // Reattach, don't respawn: on a macOS dock re-activate the window may have been
  // closed while the orchestrator stayed alive. Spawning another would overwrite
  // serverProc and leak the first. Reuse the live one and just open a window.
  if (serverProc && appUrl) {
    const win = createWindow()
    await win.loadURL(appUrl)
    return
  }
  const win = createWindow()
  try {
    // Dev-UI mode: Vite serves the renderer on 5174 and proxies /api to the Bun
    // orchestrator pinned to 8787. Otherwise the Bun server serves the built SPA.
    const devUi = !!process.env.FREEBUFF_DEV_UI
    const port = devUi ? 8787 : await findFreePort()
    serverPort = port
    // must exist before the spawn: its port/token ride the orchestrator's env
    cdpBridge = await createCdpBridge({
      getWebContents: (id) => webContents.fromId(id),
      isLoopbackHttpUrl,
    })
    // bounded and non-throwing (see signing.cjs), so awaiting it can't stall boot
    signing = await detectSigning({
      platform: process.platform,
      isPackaged: app.isPackaged,
      execPath: process.execPath,
    })
    await startOrchestrator(port)
    appUrl = devUi ? 'http://127.0.0.1:5174/' : `http://127.0.0.1:${port}/`
    // Pin the navigation/window-open guards to this exact origin.
    appOrigin = new URL(appUrl).origin
    await win.loadURL(appUrl)
  } catch (err) {
    if (err?.orchestratorFailure) {
      await showOrchestratorFailure(err.orchestratorFailure, win)
    } else {
      dialog.showErrorBox('Freebuff failed to start', String(err?.message ?? err))
    }
    app.quit()
    return
  }
  buildMenu(() => mainWindow?.loadURL(appUrl))

  // Start checking for new releases (no-op in dev; see updater.cjs). init() is
  // idempotent, so a macOS dock re-activate that re-runs boot() won't double it.
  updateChecker = updater.init({
    currentVersion: app.getVersion(),
    isPackaged: app.isPackaged,
    releaseFlavor:
      app.isPackaged &&
      path.basename(
        packagedBunPath(process.resourcesPath, process.platform),
      ).startsWith('bun-baseline')
        ? 'baseline'
        : 'standard',
    getWindow: () => mainWindow,
  })
}

// Single-instance lock — a second launch focuses the existing window.
if (!app.requestSingleInstanceLock()) {
  app.quit()
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore()
      mainWindow.focus()
    }
  })

  app.whenReady().then(boot)

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) boot()
  })

  app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit()
  })

  app.on('before-quit', stopOrchestrator)
  app.on('will-quit', stopOrchestrator)
}
